spring:
  application:
    name: test-eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    server:
#      waitTimeInMsWhenSyncEmpty: 0
#    password: 123

#cloud:
#  config:
#    uri: ${vcap.services.${PREFIX:}configserver.credentials.uri:http://user:password@localhost:8888}